### ISSUE TITLE
100 note limit?

### ISSUE THREAD

**Issue by ghost** [hiroshi/simplenote-backup#2]
Hi, great script!   

Only issue I can see is that it seems to have a 100-note limit.  I have 188 (that are NOT deleted; 425 if you include the deleted ones), and it is not getting all of my notes.  

Any idea how to fix that?

Thanks!

**Comment by hiroshi** [comment]
Hi,

@hmijail created a PR https://github.com/hiroshi/simplenote-backup/pull/1#issuecomment-252488210  and fix the issue https://github.com/hiroshi/simplenote-backup/pull/1/commits/430330c33207e18833238bcb0fc2c25640e262fe

I'v forgotten to merge the PR until now. I'll do it.

**Comment by hiroshi** [comment]
I merged #1.

So you can get it as described in README;
`git clone https://github.com/hiroshi/simplenote-backup.git`
or pull the HEAD
`cd simplenote-backup && git pull`.

I consider this issue can be closed.
If you have any trouble feel free to post a comment.
