### ISSUE TITLE
Can't retrieve token

### ISSUE THREAD

**Issue by mhalano** [hiroshi/simplenote-backup#4]
I used the Inspector on Firefox to search the string "simperium_opts.token" but I couldn't find any matches, so I couldn't get my token.

**Comment by hiroshi** [comment]
You need to enter `simperium_opts.token` into a console prompt.

If you are not familiar with web inspectors, you may learn somewhere like this site,
https://developer.mozilla.org/en-US/docs/Tools/Web_Console

I hope you can get through it ;-)
